
# BELAHOME性能指标
BELAHOME_CATEGORY_LOAD_METRIC_TIME = 2  # Belahome设备分组页面加载设备超时时间
BELAHOME_CALL_VIEW_METRIC_TIME = 5  # 通话画面加载时间指标
BELAHOME_PREVIEW_METRIC_TIME = 5  # 预览画面加载时间指标
BELAHOME_MONITOR_VIEW_METRIC_TIME = 5  # 监控画面加载时间指标
BELAHOME_MONITOR_LOCK_VIEW_METRIC_TIME = 10  # 查看门锁监控画面加载时间指标

# PANEL性能指标
PANEL_CALL_VIEW_METRIC_TIME = 5  # 通话画面加载时间指标
PANEL_PREVIEW_METRIC_TIME = 5  # 预览画面加载时间指标
PANEL_MONITOR_VIEW_METRIC_TIME = 5  # 监控画面加载时间指标


# 各端联动性能指标
SCENE_TRIGGER_DEVICE_ACTION_METRIC_TIME = 10  # 场景触发设备动作执行超时时间
